### PR TITLE
New : Added composer.json

### PR DESCRIPTION
**Pull request by vikas-srivastava**
Added composer.json file which will help this module for submission on proposed extension.silverstripe.org website. Please add more fields according to requirements.

For more information please visit at http://extension.openbees.org/instructions/

Todo  :

1 -  you also need to add "extra" field for snapshot, like

``` json
{
    ......... 
    "extra":
    {
        "snapshot" : "http://example.com/example.jpg"
    }
}
```

This will help us to showcase your module in "New Module" section.

### CODE REVIEW

**Comment by dhensby** [comment]
@chillu are we maintaining this module, do we want to pull this and submit to packagist?

**Comment by chillu** [comment]
@dhensby I think we should ask the few devs who have expressed their interest in this module (through issues or github stars) to take over this module - we're already maintaining enough of 'em, and I can't see us doing a good job on a very basic SOAP wrapper around another module (restfulserver) which will likely be superseded by a better REST API approach soon anyway.

So basically, is anybody willing to fork and register under their own namespace on Packagist.

/cc @tractorcow @camfindlay

**Comment by camfindlay** [comment]
cheers @chillu my thoughts are those that use it would be the best to take it over. So the approach in contact devs that have raised issues or forks might be the best to approach and see how we go.

**Comment by tractorcow** [comment]
I don't have any desire to support more modules, sorry, especially ones we haven't agreed to provide support for.

**Comment by chillu** [comment]
Kicked off a discussion around module support here: https://groups.google.com/forum/#!topic/silverstripe-dev/vgQZpUnxrI4

**Pull request closed without merging**
